### ISSUE TITLE
excludeRoots not working correctly for PMD

### ISSUE THREAD

**Issue by gjdev** [m2e-code-quality/m2e-code-quality#1]
When I have a configuration with
<pre>
 &lt;excludeRoots&gt;
     &lt;excludeRoot&gt;/target/generated-sources/antlr3&lt;/excludeRoot&gt;
 &lt;/excludeRoots&gt;
</pre>

the plugin translates this into
<pre>
&lt;exclude-pattern&gt;.*/C:/Users/gerjon/workspaceHel/opensahara/opensahara-apiserver.*&lt;/exclude-pattern&gt;
</pre>

Note that the actual exluded root is not part of the pattern, and also note the incorrect slash before C:

**Comment by ArloL** [comment]
Hi @gjdev,
I am trying to cleanup the issues. Is this still a problem?

**Comment by ArloL** [comment]
Since I haven't heard anything back for three months I'll go ahead and assume it works now. Otherwise simply open a new issue or reopen this one.

**Comment by vorburger** [comment]
What is slightly confusing is just that Ant style ** does not work, and most importantly the root must be complete, it seems to be implemented as equals and not startsWith, so e.g. ONLY something exactly like this works `<excludeRoots>${basedir}/target/generated-sources/mdsal-binding</excludeRoots>` but not even `${basedir}/target/generated-sources` (nor `target/generated-sources` or so). Tested on <version>3.6.
