### ISSUE TITLE
Unable to install on  Neon Milestone 2 (4.6.0M2)

### ISSUE THREAD

**Issue by aharonha** [m2e-code-quality/m2e-code-quality#102]
Hey.
I'm using Eclipse Neon M2, and I've tried to install your plug-in.
In the installation window the "finish" button is disabled.

Please assist.
Thanks

**Comment by ArloL** [comment]
Can you please try with the following update site?

https://m2e-code-quality.github.io/m2e-code-quality/site/develop/

**Comment by ArloL** [comment]
Hi @aharonha, I would like to release the changes sometime soon. Would you be able to find some time and try the `develop` update site? That way I can be confident in a release. That would be very helpful. Thanks 😄

**Comment by ArloL** [comment]
I will close this issue now. Please re-open if you are still experiencing this problem.
