### ISSUE TITLE
spotbugs support

### ISSUE THREAD

**Issue by vorburger** [m2e-code-quality/m2e-code-quality#110]
You're probably aware of [SpotBugs, the successor project of FindBugs](https://spotbugs.github.io) ?

We're adopting this in https://git.opendaylight.org/gerrit/#/c/64887/, and upon switching from the FindBugs to the SpotBugs Eclipse plugin in https://github.com/vorburger/opendaylight-eclipse-setup, I kind of hoped m2e-code-quality would "just work" (because they actually have not changed the Java packages used; it's the same code!). However it unfortunately did not work, due to:

```
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: 
   Findbugs configuration plugin for M2Eclipse 1.0.0.201501120825 (com.basistech.m2e.code.quality.findbugs.feature.feature.group 1.0.0.201501120825) 
    requires 'edu.umd.cs.findbugs.plugin.eclipse 2.0.0' but it could not be found
```

because while they appear to have kept the Java package names, they've switched the feature name.. which would have to be adapted in the m2e-code-quality dependency.

@ArloL is this something you would be willing to take care of? If not, would you welcome a PR for this, AND cut a new release with it fairly soon-ish after a PR is proposed?

**Comment by vorburger** [comment]
Opened https://github.com/spotbugs/spotbugs/issues/486 just to see if they would be willing to do something about this problem over on the "other end" of this problem... ;-)

**Comment by vorburger** [comment]
Having had a little closer look into this, it appears that the FindBugs and the SpotBugs Eclipse plugins can be installed in parallel, which is probably a Good Thing.. so the solution here could be to fork the com.basistech.m2e.code.quality.findbugs (and .feature and .test) plugins into new com.basistech.m2e.code.quality.spotbugs (and .feature and .test) ?  There are really only 4 classes, so... just copy/paste them, fine? Shame, but easiest and quickest - it would, probably, work..

PS: Adding (only) a new com.basistech.m2e.code.quality.spotbugs.feature, and have that include the com.basistech.m2e.code.quality.findbugs plugin will not work, because that has `Require-Bundle: edu.umd.cs.findbugs.plugin.eclipse;bundle-version="[2.0.0,4.0.0)"` but SBs Plugin ID is `com.github.spotbugs.plugin.eclipse`.

**Comment by ArloL** [comment]
As I have said in e.g. #97 I will accept PRs and make new releases if there is enough feedback that the code actually works - sadly my knowledge of Eclipse plugins is ***really limited*** so I don't know how to write automated tests which of course increase my confidence when releasing a new version.

**Comment by vorburger** [comment]
@ArloL FYI I've made a start for this on https://github.com/m2e-code-quality/m2e-code-quality/compare/develop...vorburger:spotbugs ... still have to do manual local testing, then I'll raise a PR. Perhaps you would like to already have a look at it though.

**Comment by vorburger** [comment]
@ArloL OK I've meanwhile manually locally tested this and it works for me! 

Would you be willing to review, hopefully merge and release https://github.com/m2e-code-quality/m2e-code-quality/pull/113/ some time?

**Comment by vorburger** [comment]
@ArloL how are you? was hoping you would have a moment to review this some time?

**Comment by hd42** [comment]
This would really help us adopt SpotBugs

**Comment by victornoel** [comment]
@ArloL any news on this? :)

**Comment by vorburger** [comment]
Are any of you 5 who thumbed up above developers will to help maintain a fork of this project?

Speak up over on https://github.com/spotbugs/spotbugs/issues/742 if you are willing to help...

**Comment by antoine-morvan** [comment]
@victornoel Hey. I'm not realy a maintainer. I just setup the update site to have CI working. I don't plan to maintain this at all (if an issue more serious than dependency version bounds arise, I might just drop M2E code quality ...). But I'd warmly welcome a serious fork :+1:
