### ISSUE TITLE
Permit any 1.x m2e version, not just up to 1.8.x?

### ISSUE THREAD

**Issue by vorburger** [m2e-code-quality/m2e-code-quality#114]
I'm not sure why m2e-code-quality limits itself to m2e version 1.0.0 - 1.8.x, with `[1.0.0,1.9.0)` ?

This makes testing it e.g. on Photon with upcoming M2E 1.9.0 from http://download.eclipse.org/technology/m2e/milestones/1.9/ difficult.. IMHO there is no real good reason to enforce this as it is currently, and it would be perfectly OK to permit any 1.x m2e version...

@ArloL would a PR proposing to change this be welcome?

**Comment by nfekete** [comment]
FYI I already submitted this change in a PR with https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin/pull/29
Nevertheless I see this change as necessary for the Photon branch, and I've been using the Photon M4 version with this change in the plugin for a while without any problems.

**Comment by nfekete** [comment]
Sorry, I commented on the wrong issue.

**Comment by vorburger** [comment]
done in #115.
