### ISSUE TITLE
Incompatible with maven-checkstyle-plugin 3.0.0

### ISSUE THREAD

**Issue by reckart** [m2e-code-quality/m2e-code-quality#117]
When used with the maven-checkstyle-plugin version 3.0.0, the file sets are generated without the default patterns

```
^src/main/java/.*\.java
^src/test/java/.*\.java
```

Downgrading the maven-checkstyle-plugin to 2.17 and updating the Maven configuration all the affected projects in Eclipse resolves the issue again.

Cf. https://marketplace.eclipse.org/comment/5105#comment-5105

**Comment by impidimpi** [comment]
I guess this has to do with https://issues.apache.org/jira/browse/MCHECKSTYLE-336.

sourceDirectory - Deprecated. instead use sourceDirectories. For version 3.0.0, this parameter is only defined to break the build if you use it!

See: com.basistech.m2e.code.quality.checkstyle.MavenPluginConfigurationTranslator.getSourceDirectories()

**Comment by adrienrivard** [comment]
As a workaround you can add :
```
<sourceDirectories>${project.compileSourceRoots}</sourceDirectories>
<testSourceDirectories>${project.testCompileSourceRoots}</testSourceDirectories>
```
to the maven-checkstyle-plugin configuration in the pom.xml

**Comment by jodastephen** [comment]
The fork of this plugin from [GEBIT](https://github.com/GEBIT/m2e-code-quality/tree/develop) also seems to solve this. I've uploaded a binary zip to my [eclipse-setup](https://github.com/jodastephen/eclipse-setup) repo.

**Comment by erwint** [comment]
I'll add all our changes as a PR, now that there's activity again. I'm not aware of a fix for this one, probably a side effect of another change
