### ISSUE TITLE
Dependabot

### ISSUE THREAD

**Issue by vorburger** [m2e-code-quality/m2e-code-quality#128]
To whom it may concern:

I have set up https://dependabot.com on this project.

Am using it elsewhere, and finding it useful.

Set it to automatically merge - first time.

**Comment by vorburger** [comment]
https://app.dependabot.com/accounts/m2e-code-quality/repos says:

> Error bumping dependencies
> 
> Dependabot encountered an unknown error.
> 
> We've been notified of the problem, and are working to fix it.

@greysteil wanna check your logs to see what's causing this? 

FYI this is a Maven build for an Eclipse plugin, using https://www.eclipse.org/tycho/ ...

**Comment by greysteil** [comment]
I’ll take a look

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/03e04ddbfce1ec7d7fb4ca41b52bbc82aae18502, which is deploying now. I'll manually trigger an update run on this repo once it's deployed. 🤖

**Comment by vorburger** [comment]
@greysteil thanks!! Seems to work great now, see #132 and #133 - so closing as Done.
