### ISSUE TITLE
Change Update Site URL in feature.xml sources from old to new CD site

### ISSUE THREAD

**Issue by vorburger** [m2e-code-quality/m2e-code-quality#137]
Following #123, we now have 2 update sites:

* new, and CD'd: https://m2e-code-quality.github.io/m2e-code-quality-p2-site/
* old original and not going to be maintained (at least by me): http://m2e-code-quality.github.io/m2e-code-quality/site

While reviewing @erwint's #136 I noticed that the feature.xml source still contain the old one. Should we be replacing it (not in #136 but afterwards, everywhere) with the new one (after someone confirms it works) ?

Any thoughts @erwint @victornoel @ArloL ?

**Comment by victornoel** [comment]
@vorburger I agree we should use the new one once we are sure it works
