### ISSUE TITLE
Redirect old to new CD update site?

### ISSUE THREAD

**Issue by vorburger** [m2e-code-quality/m2e-code-quality#143]
further to #137 re. our old VS new p2 update site:

seeing @antoine-morvan link to https://github.com/preesm/m2e-code-quality/commit/2a3742207f799bfb20e2897e217ace5ee2be8894 in https://github.com/m2e-code-quality/m2e-code-quality/issues/120#issuecomment-422816082 (thanks), I'm wondering if the same p2 redirect `<child location=` thing in `compositeArtifacts.xml` should somehow be done to https://github.com/m2e-code-quality/m2e-code-quality/tree/gh-pages/site ? Perhaps preserve old versions there as is, but make anyone grabbing the latest one redirect to https://m2e-code-quality.github.io/m2e-code-quality-p2-site/ ?

My p2 understanding is too rusty to know exactly how to do that, but if @antoine-morvan would contribute a PR ... that could be cool, and will perhaps avoid some confusion in the future to people.

@erwint @victornoel @ArloL thoughts - any reason why we should not do this that I cannot think of?

**Comment by victornoel** [comment]
@vorburger I agree it' a good idea, but I can't help in practice, I've never understood how all those things worked in p2, I tried, but I never succeeded :P

**Comment by antoine-morvan** [comment]
Hey, I'll have a look at this (I'll let you change the index.html files with proper guidelines).

Basically you want the old P2 repo to serve the current releases it has (that is pre-Photon compatible) plus the new repo with Photon+ compatible, right ?

**Comment by vorburger** [comment]
> I'll let you change the index.html files with proper guidelines

#144

> Basically you want the old P2 repo to serve the current releases it has (that is pre-Photon compatible) plus the new repo with Photon+ compatible, right ?

Yeah. Except that I assumed that the new repo is also still compatible pre-Photon... I didn't think we already broke that? :smile:

**Comment by vorburger** [comment]
> the new repo with Photon+ compatible, right ?

@antoine-morvan FYI @pgalbraith has done some compatiblity testing, see https://github.com/m2e-code-quality/m2e-code-quality/issues/123#issuecomment-422867170.

**Comment by antoine-morvan** [comment]
Yeah my bad, I meant the old repo is pre-photon only and the new is pre+post photon compatible.

Do you also want the new repo to serve the releases from the old one ?

**Comment by vorburger** [comment]
> Do you also want the new repo to serve the releases from the old one ?

yeah, but as per #155

**Comment by erwint** [comment]
Should be fixed now that #155 is merged. Can we close this?

**Comment by vorburger** [comment]
> Should be fixed now that #155 is merged. Can we close this?

yep! Thank you.
