### ISSUE TITLE
Allow parallel building

### ISSUE THREAD

**Issue by vorburger** [m2e-code-quality/m2e-code-quality#168]
inspired by seeing https://github.com/checkstyle/eclipse-cs/pull/109

see e.g. https://de.slideshare.net/mickaelistria/parallel-builds-in-eclipse-ide-workspace

Is this something that would also make sense for this project? Any volunteers to do this?

@Bananeweizen @erwint @adangel

**Comment by Bananeweizen** [comment]
@vorburger Michael, I don't really know. :) The respective change is relevant for IncrementalProjectBuilder subclasses. If this project uses such a builder to participate in workspace builds, then it probably makes sense here, too.

**Comment by vorburger** [comment]
I just had a quick closer look, and we actually don't implement any Eclipse Builders in this project, just Project Configurators. So this is a non-issue; closing this.
