### ISSUE TITLE
Eclipse 2018-09

### ISSUE THREAD

**Issue by anton-johansson** [m2e-code-quality/m2e-code-quality#170]
I just tried installing this in a fresh Eclipse 2018-09 (latest version) and I got some errors that looks very similar to what we got in #120.

That issue was fixed and it **should** be compatible with Eclipse 2018-09. Maybe [the repository page](https://m2e-code-quality.github.io/m2e-code-quality-p2-site/) just isn't updated with the latest version?

For now I just went with [this fork](https://github.com/jesse-gallagher/m2e-code-quality) with [this repository](https://preesm.github.io/m2e-code-quality/site/latest/) which has the same fix, and that worked.

**Comment by Serranya** [comment]
I have more or less the same issue.
org.eclipse.m2e.jdt 1.9.1 is installed and therefor I also geht the Missing requirement error.

**Comment by vorburger** [comment]
@anton-johansson the the repository page you link to above is preesm.github.io .. not sure who or what @preesm is, but that is not this project. Probably on old and long outdated fork - @preesm would you be willing to take that down, or make it point to us instead? Likewise for @jesse-gallagher's fork which you link to.

This project's latest update site is (now) https://m2e-code-quality.github.io/m2e-code-quality-p2-site/, just like it says in the _Download_ section on http://m2e-code-quality.github.io/m2e-code-quality/ ... not sure how to make that more explicit and clear? :smiling_imp: 

@erwint if that's not it, can you help @anton-johansson and @Serranya ?

@anton-johansson and @Serranya OK to close this issue?

**Comment by anton-johansson** [comment]
@vorburger:

I'm well aware of it being an older fork. I must've gotten the wrong link in my clipboard. Fixed now.

Anyway, the update site that I tried at first is the same one you linked, and it's the one I got the error from. I do know that the fix from @preesm is merged to this repository, what I was wondering is if the update site (https://m2e-code-quality.github.io/m2e-code-quality-p2-site/) is updated?

So no, I'm not OK with closing the issue just yet. :D As I said, I got it working with the @preesm update site, but that won't be accepted as easily for the rest of my organisation.

**Comment by vorburger** [comment]
> what I was wondering is if the update site
> (https://m2e-code-quality.github.io/m2e-code-quality-p2-site/) is updated?

yeah, so https://m2e-code-quality.github.io/m2e-code-quality-p2-site/ = https://github.com/m2e-code-quality/m2e-code-quality-p2-site which gets updated automatically from every commit to master by Travis, see #123 (and #124 for more history; also #155 for #143 for a possible future "stable" site).

So the version range `"[1.0.0,2.0.0)"` for the required org.eclipse.m2e.* bundles in all the `MANIFEST.MF` looks good to me. If anyone would post the exact actual error you guys are seeing, perhaps that would be a more helpful start to understand what's really going on here... @erwint your help here most welcome!

**Comment by anton-johansson** [comment]
Allright, so it should be up to date... Strange.

Let me try it again in a fresh 2018-09 as soon as I have some spare time and get the exact error message.

**Comment by Serranya** [comment]
Argh. I did indeed use the wrong update site.

I used the first one google found and didn't take a look at the projekt page.

**Comment by vorburger** [comment]
@Serranya so it works for you now, have you retried? 

@anton-johansson sure. Hope it's fair if we close this issue in 1 week if no news.

**Comment by anton-johansson** [comment]
@vorburger: Sure, I haven't had time to re-try it yet... But just close it now if you want, and I can ping you for re-open if/when I reproduce it and supply full logs.

**Comment by Serranya** [comment]
It's working for me now :)
