### ISSUE TITLE
Automatic release recreates JARs for tagged version

### ISSUE THREAD

**Issue by vorburger** [m2e-code-quality/m2e-code-quality#179]
@erwint I hadn't closely looked at the work you did in #176 (thank you BTW!), but when I just looked at https://github.com/m2e-code-quality/m2e-code-quality-p2-site, I thought it was curious that both the `/snapshot/` as well as the `/1.1.0/` just seem to have gotten updated, following my merge of #177 ... isn't `/1.1.0/` supposed to not move anymore now?

It's not a real problem for me, as I'm personally just using https://m2e-code-quality.github.io/m2e-code-quality-p2-site/snapshot/ only anyway :smiley: but I thought it may worth pointing this out and clarify, for anyone interested in "released" and stable versions. (And do feel free to just close this issue if clarified that this is not a real issue!)

**Comment by erwint** [comment]
if you look closely, the artifacts in /1.1.0 are still the original ones (look at the qualifier, e.g. com.basistech.m2e.code.quality.checkstyle.feature_1.1.0.201811102243-r.jar). That's just how the `pages` [deployment in Travis ](https://docs.travis-ci.com/user/deployment/pages/) works, it can only completely replace the current branch.

**Comment by vorburger** [comment]
Oh! I see. Thanks for the clarification.
