### ISSUE TITLE
sourceDirectory and testSourceDirectory are not supported for CheckStyle

### ISSUE THREAD

**Issue by kmatoski** [m2e-code-quality/m2e-code-quality#18]
The plugin always defaults the CheckStyle file sets to the src/main/java folder. It would be nice to fully support the maven-checkstyle-plugin and be able to extract the file sets directories from sourceDirectory and testSourceDirectory properties.

**Comment by ArloL** [comment]
This should work now. Please open a new issue if there are any problems
