### ISSUE TITLE
For inline configuration use header from maven

### ISSUE THREAD

**Issue by Serranya** [m2e-code-quality/m2e-code-quality#192]
We should use the header string from maven introduced in https://github.com/apache/maven-checkstyle-plugin/commit/0de3460e15e07a529f26cd69b3d2eb24e3e18310 for the reasons outlined in https://github.com/apache/maven-checkstyle-plugin/pull/7.

**Comment by vorburger** [comment]
sorry from a 23s glance over the linked issues I'm not getting what this is about, but if you want to raise a PR proposing something, I'm sure @erwint and others would be happy to review and possibly merge it ...

FYI there were previous discussions re. reporting in #118, if that is relevant to you here.

**Comment by Serranya** [comment]
Yeah, I will open a PR.

The problem is:

we pass the inline checkstyle configuration to checkstyle as a xml file. This file needs to include a DTD header. But the header is different depending on the checkstyle version.

We could hardcode the known headers, but we would need to update this plugin everytime checkstyle updates their header.

Thats why the maven plugin specifies a default header and lets the user override it.

We should read the header value from the maven config and use that one instead of our hardcoded one:
https://github.com/m2e-code-quality/m2e-code-quality/blob/9cd1683b94fe94b535b2c381801b535bd68b3487/com.basistech.m2e.code.quality.checkstyle/src/main/java/com/basistech/m2e/code/quality/checkstyle/MavenPluginConfigurationTranslator.java#L77-L80

**Comment by Serranya** [comment]
I just opened this issue so I don't forget to fix this.
