### ISSUE TITLE
pmd excludeRoots is not working

### ISSUE THREAD

**Issue by Flugtiger** [m2e-code-quality/m2e-code-quality#196]
If specifying excludeRoots in pom.xml, it has no effect on the generated .pmdruleset.xml

Reason: in MavenPluginConfigurationTranslator#buildExcludeAndIncludeSourceRoots the local variable 'excludeRootsFromConfig' is never added to the field 'excludeSourceRoots'

**Comment by vorburger** [comment]
>
> in MavenPluginConfigurationTranslator#buildExcludeAndIncludeSourceRoots
> the local variable 'excludeRootsFromConfig' is never added to the field
> 'excludeSourceRoots'
>
Thanks for finding this. Would you like to raise a Pull Request addressing
this? I would be very happy to merge it quickly.

**Comment by Flugtiger** [comment]
I'll give it a try :-)

**Comment by vorburger** [comment]
@Flugtiger really sorry it took so long to merge this - I forgot about this and saw it now by chance.

Please keep your contributions coming - we'll make you a committer quickly... :smile:
