### ISSUE TITLE
exludes does not work for PMD

### ISSUE THREAD

**Issue by gjdev** [m2e-code-quality/m2e-code-quality#2]
When I have &lt;exludes&gt; in my maven-pmd-plugin config, they are skipped by this eclipse plugin, saying that because there are also &lt;includes&gt; the excludes will be ignored. This message is there even when I have no includes section in my config at all, or when I have an empty includes section in my config.

**Comment by ArloL** [comment]
Same question here, @gjdev. Is this still a problem? Please let me know and I will look into it.

**Comment by ArloL** [comment]
Since I haven't heard anything back for three months I'll go ahead and assume it works now. Otherwise simply open a new issue or reopen this one.
