### ISSUE TITLE
target platform does not contain commons.lang

### ISSUE THREAD

**Issue by Bananeweizen** [m2e-code-quality/m2e-code-quality#203]
Neither the Oxygen nor Photon .target files contain org.apache.commons.lang, but it is used in the checkstyle plugin. How does this compile for others?
There are multiple options for fixing this:
* add Orbit to the URL list in the target files
* recreate the targets from TPD files, which allow much better control of the content
If you advise me on some preferred solution, I might be able to contribute it myself.

PS: Any objections to replacing commons.lang with commons.lang3 in the process?

**Comment by vorburger** [comment]
> How does this compile for others?

I'm not 100% sure the CLI mvn build actually uses the .target files... there is probably potential for some clean up.

> PS: Any objections to replacing commons.lang with commons.lang3 in the process?

as long as everything still works, do whatever you think needs to be done / you feel like doing!
