### ISSUE TITLE
Invite additional committers

### ISSUE THREAD

**Issue by vorburger** [m2e-code-quality/m2e-code-quality#208]
In order to continue #124 _("[keep the lights on this project](http://blog2.vorburger.ch/2019/02/about-you-and-that-open-source-thing.html)"),_ and in the spirit of a truly open project with a low barrier to entry (and also to avoid myself being the bottleneck and single active reviewer on this project...), I'd like to open an invitation to a few additional [people who all made a handful of contributions recently](https://github.com/m2e-code-quality/m2e-code-quality/graphs/contributors) to become additional committers to this project:

* @bananeweizen ([recent contributions](https://github.com/m2e-code-quality/m2e-code-quality/commits?author=Bananeweizen))
* @serranya ([recent contributions](https://github.com/m2e-code-quality/m2e-code-quality/commits?author=Serranya))
* @adangel ([recent contributions](https://github.com/m2e-code-quality/m2e-code-quality/commits?author=adangel))
* @victornoel ([recent contributions](https://github.com/m2e-code-quality/m2e-code-quality/commits?author=victornoel))
* @pgalbraith ([recent contributions](https://github.com/m2e-code-quality/m2e-code-quality/commits?author=pgalbraith))

@erwint you are the only other recently active commiter (with me), and I'll just assume that you would be OK with this... please scream and shout should you strongly feel that this is the wrong approach.

I have invited all x5 above via GitHub - but please do feel absolutely free to not accept the invite - I'll [remove the invitation](https://github.com/orgs/m2e-code-quality/people) again in 2 weeks or so. If you accept, please enable 2FA on our GH. The expectation the project has to you is very low :smile_cat: ... just that you help occasionally review and merge PRs from others. I suggest that generally we don't "self merge", but more as a guidance than as a hard rule - I think self merging trivial changes is actually OK. Of course, don't break the build (or functionality) - but thanks to git we can of course easily just revert anything that broke things easily. As this is typically quite rare, I think it's OK to liberally let contributors merge.

**Comment by vorburger** [comment]
FTR: @erwint and myself (@vorburger) are "Owners" of the Org, and the invitations are as "Members".

**Comment by Serranya** [comment]
Thanks for the invite. I will try to help where I can.

**Comment by Bananeweizen** [comment]
Thanks, that sounds good me. Honestly, I'm not sure if I'll be around often enough due to other open source activities, but if it doesn't work out well, I will also not be crying my eyes out, if I'm removed from those privileges again after some time. :) Generally I like this "make it easy to join" attitude of yours, since many projects suffer from a high barrier to entry.

**Comment by erwint** [comment]
Of course I'm okay with this :+1:

**Comment by vorburger** [comment]
Everyone listed above excepted @victornoel has meanwhile accepted the invitation.

I've removed @victornoel invite, just as a general security best practice; happy to re-invite you any time.

**Comment by victornoel** [comment]
@vorburger yep thx for the invite, didn't have the time to look at all this for some time, I will linger around but I'm good not being in the organisation :)
