### ISSUE TITLE
Checkstyle configurator does not support <suppressionsLocation> pom value

### ISSUE THREAD

**Issue by jodastephen** [m2e-code-quality/m2e-code-quality#22]
Checkstyle's suppressions file should be [configured](http://maven.apache.org/plugins/maven-checkstyle-plugin/check-mojo.html#suppressionsLocation) using `suppressionsLocation` and `suppressionsFileExpression` as per [this guide](http://maven.apache.org/plugins/maven-checkstyle-plugin/examples/suppressions-filter.html).

The necessary fix is almost certainly simlar to #14 and #15.

Current workaround is to use `propertyExpansion` which only works properly on Windows using the "hidden" 1.0.0 release site.

**Comment by ArloL** [comment]
Is this issue still relevant?

**Comment by jodastephen** [comment]
I haven't tested to see if the patch has fixed it, but I imagine it has.

**Comment by ArloL** [comment]
Thanks for reporting back. OK. Then I will close the issue.

Just open a new one if you have any problems!
