### ISSUE TITLE
Incorrect PMD ruleset configuration file name

### ISSUE THREAD

**Issue by lennartj** [m2e-code-quality/m2e-code-quality#23]
Corrected the m2e-generated ruleset name, from .ruleset to .ruleset.xml

This prevents PMD from messing up the interpreted path to the generated configuration through some arcane assumptions about how to treat certain characters in the path.

Patch supplied in the commit ca220ed33fa6598ad75e847b4dd9f7346aa1b8f0, on the `pmd-eclipse-plugin-4.0.0 branch` in `lennartj / m2e-code-quality` repo.

Feel free to merge...

**Comment by ArloL** [comment]
Apparently this was fixed with https://github.com/m2e-code-quality/m2e-code-quality/commit/495334764cfaaf0ecf4d26b16d68639786bee5f0#diff-f6ee209af9280b61263d989f5209c628. Thanks, @lennartj.
