### ISSUE TITLE
Wrong Checkstyle URL breaks Oomph setup

### ISSUE THREAD

**Issue by famod** [m2e-code-quality/m2e-code-quality#251]
We have (well, had) this in our project Oomph setup file:
![P2](https://user-images.githubusercontent.com/22860528/124661794-49440a80-dea8-11eb-962d-651d8041e7ff.png)

Due to the demise of bintray, this brings in now broken update sites for eclipse-cs (and with `1.1.4.201906210825-r` also pmd), which in turn breaks "Check for Updates" or "Perform Setup Tasks..." (when P2 Directors are run).
Removing those broken sites is of no real use since they come back with each "Perform Setup Tasks...".

As a quick hack I did the following and lo and behold, it worked: https://github.com/m2e-code-quality/m2e-code-quality/compare/develop...famod:fix-urls
Changes:
- fixed eclipse-cs URL
- switched download.eclipse.org to https (but still seeing a few download errors in console while building via `mvn`, but site is built properly)
- changed plugin repo in pom because https://mvnrepository.com/artifact/org.jboss.tools.tycho-plugins/repository-utils?repo=jboss-ea cannot be found

Take this with a grain of salt because I didn't run any tests (`-DskipTests`).

**Comment by vorburger** [comment]
Why not directly raise a PR instead of a bug?

Would you be interested to be invited as a committer to this project to help maintain it?

**Comment by famod** [comment]
> Why not directly raise a PR instead of a bug?

Because I didn't run any tests and I'm lacking the knowledge of eclipse plugin development. Sadly, I don't have the time to work my way into this either, ATM.

**Comment by vorburger** [comment]
@adangel fixed this in #255 (I think, re-open if NOK for you).

**Comment by adangel** [comment]
Fixed with f15dc18
With #255 only the build was fixed, but not the oomph setup file.

**Comment by famod** [comment]
I'm afraid that even with `1.1.5.202109180907-r` im getting bintray entries, breaking updates etc.

oomph-setup:
![oomph](https://user-images.githubusercontent.com/22860528/140390177-1f616869-8037-4a61-960d-1eb3921ffe35.png)

![sites](https://user-images.githubusercontent.com/22860528/140390426-af808e67-5b1f-4a8b-8c15-99a3c4a4e5e6.png)

PS: Eclipse 2021-09.
