### ISSUE TITLE
exclude generated source folders from checkstyle

### ISSUE THREAD

**Issue by jpraet** [m2e-code-quality/m2e-code-quality#27]
The maven-checkstyle-plugin only passes the project.build.sourceDirectory to checkstyle. m2e-code-quality-checkstyle however passes all compile source directories returned from mavenProject.getCompileSourceRoots() to checkstyle. This includes generated sources directories such as target/generated-sources/jaxb.

**Comment by ArloL** [comment]
Hi @jpraet, @trajano and @khozzy,

I am trying to cleanup the issues and I was wondering whether this issue has been fixed with the recent release?

**Comment by jpraet** [comment]
It is no longer an issue with the latest release.

**Comment by ArloL** [comment]
Thanks for your feedback, @jpraet. I will close this issue then.
