### ISSUE TITLE
Spotbugs - new mojo 'verify' coming for 4.7.0

### ISSUE THREAD

**Issue by hazendaz** [m2e-code-quality/m2e-code-quality#278]
Hi, I'm the maintainer of spotbugs maven plugin.  The next minor release of spotbugs plugin will introduce a new mojo verify, see https://github.com/spotbugs/spotbugs-maven-plugin/pull/405.  Support for same should be added here, I can raise a PR for this effort and PR should be held until this is official.  Most likely will just put the PR in draft status, please let me know if that is ok and I'll get it out here.  Thanks.

**Comment by adangel** [comment]
Hi @hazendaz , sorry for the late response.

Yes, PRs are welcome, thanks!

**Comment by adangel** [comment]
Fixed by #343

**Comment by adangel** [comment]
won't fix as it is not needed, see https://github.com/m2e-code-quality/m2e-code-quality/pull/343#issuecomment-2057469516
