### ISSUE TITLE
Update to Eclipse 2022-09 / m2e 2.0

### ISSUE THREAD

**Issue by hd42** [m2e-code-quality/m2e-code-quality#293]
Eclipse 2022-09 uses m2e 2.0.4, which requires Java 17 and the Maven 3 API. This is probably incompatible and might require a m2e-code-quality 2.0 release

**Comment by adangel** [comment]
Thanks for reporting, this is a duplicate of #292.

**Comment by adangel** [comment]
Hi @hd42, I've just released version 2.0.0 which fixes this issue - please update m2e-code-quality from https://m2e-code-quality.github.io/m2e-code-quality-p2-site/

**Comment by hd42** [comment]
Thank you for the quick update, it seems to be working fine.
