### ISSUE TITLE
Mistake in double star whildcard conversion

### ISSUE THREAD

**Issue by tmortagne** [m2e-code-quality/m2e-code-quality#30]
The maven checkstyle plugin exclude ``org/xwiki/test/ui/**/*.java`` end up in the eclipsecs configuration as ``src/main/java.*org/xwiki/test/ui/.*/.*\.java`` which does not includes Java files located in ``org/xwiki/test/ui/``.

In this case the expected conversion would be ``src/main/java.*org/xwiki/test/ui/.*\.java`` I guess.

**Comment by ArloL** [comment]
Hi @tmortagne,

I am trying to cleanup the issues of the project. Is this still an issue?

**Comment by tmortagne** [comment]
I can still reproduce the issue with version 1.0.0.201602071612.

**Comment by tmortagne** [comment]
The issue is indeed fixed, I now end up with `src/main/java.*org/xwiki/test/ui/.*\.java` on Eclipse side.

**Comment by ArloL** [comment]
Thanks for your feedback, @tmortagne. I will close this issue then.
