### ISSUE TITLE
When using a dependent configuration, Checkstyle becomes disabled

### ISSUE THREAD

**Issue by trajano** [m2e-code-quality/m2e-code-quality#32]
Given the following configuration

		<pluginManagement>
			<plugins>
				<plugin>
					<artifactId>maven-checkstyle-plugin</artifactId>
					<version>2.10</version>
					<configuration>
						<configLocation>config/checkstyle-configuration.xml</configLocation>
					</configuration>
					<dependencies>
						<dependency>
							<groupId>net.trajano</groupId>
							<artifactId>coding-standards</artifactId>
							<version>1.0.1-SNAPSHOT</version>
						</dependency>
					</dependencies>
				</plugin>
			</plugins>
		</pluginManagement>

And this profile

    <profiles>
		<profile>
			<id>m2e</id>
			<activation>
				<property>
					<name>m2e.version</name>
				</property>
			</activation>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-checkstyle-plugin</artifactId>
						<executions>
							<execution>
								<id>check</id>
								<phase>compile</phase>
								<goals>
									<goal>check</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

The plug-in does not configure checkstyle to be active on the project.

**Comment by ArloL** [comment]
Out of curiosity: why do you only activate checkstyle if m2e.version is present?

Could you try the latest develop build:

http://m2e-code-quality.github.io/m2e-code-quality/site/develop/

**Comment by trajano** [comment]
There are only two times I want the checkstyle to run in order to speed up the build process.
1. the site report
2. within the IDE so the developers can fix the problems ASAP

I don't normally let style checks fail the build, because rules can be in flux and may need to be discussed.  So we leave it as technical debt until we resolve the problem or update the rule.

**Comment by ArloL** [comment]
The goal checkstyle:checkstyle should trigger the connector to configure checkstyle. So you don't need the additional profile.

**Comment by trajano** [comment]
If I don't have the additional profile checkstyle executes on the command line builds by default which I want to avoid.

**Comment by ArloL** [comment]
What I mean is that the report goal should trigger the configuration. Thus it won't run in your regular mvn build and only during site. But it should still configure eclipse-cs.

**Comment by trajano** [comment]
Ah okay I will try that out.

**Comment by trajano** [comment]
Error seems to be a bit worse now
<pre>
Errors occurred during the build.
Errors running builder 'Checkstyle Builder' on project 'jetng-maven-plugin'.
cannot initialize module TreeWalker - Unable to instantiate RedundantThrows
cannot initialize module TreeWalker - Unable to instantiate RedundantThrows
cannot initialize module TreeWalker - Unable to instantiate RedundantThrows
cannot initialize module TreeWalker - Unable to instantiate RedundantThrows
</pre>

**Comment by ArloL** [comment]
Hi @trajano, I pushed an update recently. I was wondering whether your problem still exists?

**Comment by ArloL** [comment]
Since I haven't heard anything back for three months I'll go ahead and assume it works now. Otherwise simply open a new issue or reopen this one.

**Comment by trajano** [comment]
Sounds good, I haven;t been on a proejct that required it for a while so I wasn't able to test.
