### ISSUE TITLE
Incompatible with latest PMD plugin

### ISSUE THREAD

**Issue by rdicroce** [m2e-code-quality/m2e-code-quality#327]
PMD is working towards a final 7.0.0 release, and it looks they have bumped the version of their Eclipse plugin so it now aligns with the PMD version. But m2e-code-quality requires version range [4.0.0, 5.0.0) so Eclipse cannot install both at the same time.

**Comment by adangel** [comment]
Thanks for the report.
This is already taken care by #320 .
You can install the snapshot version of m2e-code-quality from here https://m2e-code-quality.github.io/m2e-code-quality-p2-site/snapshot/ which contains the fix already.

For the changelog of the snapshot build, see https://m2e-code-quality.github.io/m2e-code-quality-p2-site/snapshot/CHANGELOG.html
