### ISSUE TITLE
m2e-code-quality-bot 2FA, and or delete?

### ISSUE THREAD

**Issue by vorburger** [m2e-code-quality/m2e-code-quality#336]
GitHub keeps spamming me to enable 2FA for https://github.com/m2e-code-quality-bot.

I kinda forgot what I had originally created that account for, and more importantly, if this Org still uses it anywhere? 

Could I just delete it now? Anyone reading this, any 💭 thoughts, reactions, objections?

See also #302 

@adangel

**Comment by vorburger** [comment]
#282 said okay to delete old bot already, I just noticed... re-confirm, please?

**Comment by adangel** [comment]
Yes, just delete the bot account. If something breaks, we just need to fix it. But I don't think, the account is used anywhere.

**Comment by vorburger** [comment]
> Yes, just delete the bot account. If something breaks, we just need to fix it. But I don't think, the account is used anywhere.

Done; https://github.com/m2e-code-quality-bot is now 404.
