### ISSUE TITLE
Proper releases instead of just snapshots?

### ISSUE THREAD

**Issue by famod** [m2e-code-quality/m2e-code-quality#341]
I'd really appreciate it if you would start doing "proper" releases again.

The last one was 2.0.0 back in 09/2022, but since then only snapshots have been published.
I'm grateful for these snapshots, but snapshots are like snowflakes - they can vanish at any time, harming reproducibility of Eclipse setups over time. And when pinning a snapshot version in an oomph setup file, you will end up with an error once that snapshot is removed from the update site when a new snapshot is published.
Also, there is no proper changelog for those snapshots.

Thanks & cheers!

**Comment by adangel** [comment]
I can do a release of the current state as 2.1.0.
Btw - the changelog of the snapshot is here: https://m2e-code-quality.github.io/m2e-code-quality-p2-site/snapshot/CHANGELOG.html

**Comment by adangel** [comment]
Will start the release now...

**Comment by famod** [comment]
Cool, thanks!

I think it would make sense to create a github release entry as well, otherwise it looks like 2.0.0 is still the latest one.

**Comment by adangel** [comment]
working on it... seems some script failed

**Comment by adangel** [comment]
ok, should have closed this issue _before_ I created/pushed the tag. That caused the script to generate the release notes for the next version already... that's why the release notes looks weird.

It's there now: https://github.com/m2e-code-quality/m2e-code-quality/releases/tag/2.1.0
