### ISSUE TITLE
can't get checktsyle integration working in eclipse

### ISSUE THREAD

**Issue by cforce** [m2e-code-quality/m2e-code-quality#36]
We installed latest from "https://github.com/m2e-code-quality/m2e-code-quality/tree/gh-pages/site/latest" update site, but chechstyle don't works or nothinh happens .

We use
Eclipse 4.3.1 with maven 3.1 checktsyle plugin inside and outside of reports section, bound to compile phase at goald check and checktsyle using an external checkstyle config path from sonar server (https with verisign cert but access without http authentification possible)
.
There is no noise of checktsyle at the maven console.
Is there any more dialog or appearacne on the settings . I am missing screenhosts and docu which shows/desribes what shall happen. 
If i call the chekctsyle plugin manually from maven console it works fine, but eclipse doesn't do anything.
I also would expect the plugin to add new check config (in our case remote cfg) in the eclipse settings> checktsyle dialog. Buts its simply unclear what this plugin does and what not. Please add some screenhshots showing the result of a working integration too.

**Comment by ArloL** [comment]
Hi @cforce,

I am going through all the issues of the project and am trying to see whether they still exist. Is this still a problem?

**Comment by ArloL** [comment]
Since I haven't heard anything back for three months I'll go ahead and assume it works now. Otherwise simply open a new issue or reopen this one.
