### ISSUE TITLE
Incompatibilities with maven-checkstyle-plugin 2.13

### ISSUE THREAD

**Issue by Dawuid** [m2e-code-quality/m2e-code-quality#52]
The plugin maven-checkstyle-plugin:2.13 has been published recently and there are changes that conflicts with present m2e-code-quality version (I suppose). Now source and test directories are directories, not a single one. Changes are needed to deal with that in MavenPluginConfigurationTranslator.java (parameter String sourceDirectory is now List<String> sourceDirectories, and similar with testSourceDirectory).

I have done a little patch but is only compatible with 2.13, not previous versions (https://github.com/Dawuid/m2e-code-quality/compare/m2e-code-quality:master...master) so I think is not worth a pull request (I was trying an early combination of m2e-code-quality + checkstyle 5.8 modified for java8 + eclipse luna + eclipse checkstyle plugin for java 8 testing).

**Comment by ArloL** [comment]
We have stayed at maven-checkstyle-plugin 2.12 due to the changes introduced in 2.13.

So sadly I have to tell you that I won't be looking into 2.13 compatibility. Maybe 2.14 will be better.

**Comment by ArloL** [comment]
I should read properly. I just saw the PR.

I will of course look into it.

**Comment by ArloL** [comment]
Please test with this update site: http://m2e-code-quality.github.io/m2e-code-quality/site/develop/

**Comment by Dawuid** [comment]
Working like a charm with java8+checkstyle 6.1.1, thank your very much to both.

PS: maven-checkstyle-plugin is not being actively maintained for months (only few commits, not so serious)

**Comment by ArloL** [comment]
Then I will make a release.

Yes, I know. That's really sad but I can't maintain everything. I was kinda "tricked" into being the maintainer of m2e-code-quality already :smile:

**Comment by ArloL** [comment]
Fixed with latest release.
