### ISSUE TITLE
suppressionsLocation conflicting between maven and eclipse

### ISSUE THREAD

**Issue by jpraet** [m2e-code-quality/m2e-code-quality#54]
The maven-checkstyle plugin puts the suppressions file in `${project.build.directory}` with the name `checkstyle-supressions.xml`. 

The m2e-code-quality plugin puts the suppressions file in the same directory, but it adds the execution id to the name, `checkstyle-suppressions-{executionId}.xml`.

When you launch a maven build outside of eclipse, the target directory is cleared, so the `checkstyle-suppressions-{executionId}.xml` gets deleted.

This then results in the following type of error in eclipse:
`Errors running builder 'Checkstyle Builder' on project 'xyz'.
cannot initialize module SuppressionFilter - Cannot set property 'file' in module SuppressionFilter to 'D:\projects\xyz\target\checkstyle-suppressions-default.xml': unable to find D:\projects\xyz\target\checkstyle-suppressions-default.xml`.

Doing a `Maven -> Update Project...` in eclipse creates the `checkstyle-suppressions-{executionId}.xml` again and thus solves the problem. But you have to do this after each maven build.

A possible solution could be to put the suppressions file in the eclipse `.settings` directory instead of the maven target directory.

**Comment by moldowan** [comment]
I have been using this patch for a couple of weeks without problems. This should be included in the next release!

**Comment by victornoel** [comment]
@ArloL any way to merge this PR and release a new version? Thanks

**Comment by jpraet** [comment]
Can this be merged and released please?

**Comment by dbevacqua** [comment]
+
