### ISSUE TITLE
upgrade to checkstyle > 6.0

### ISSUE THREAD

**Issue by u3r** [m2e-code-quality/m2e-code-quality#58]
The default updatesite for eclipse checkstyle http://eclipse-cs.sourceforge.net/update/ now only references versions > 6.0, so you have to manually tweak versions. (At least when automatically preparing an eclipse distribution)

**Comment by ArloL** [comment]
Please try this site http://m2e-code-quality.github.io/m2e-code-quality/site/develop/ and tell me whether it works.

**Comment by ArloL** [comment]
I have released a new version: http://m2e-code-quality.github.io/m2e-code-quality/site/latest

Please open a new issue if you have any problems.
