### ISSUE TITLE
createPmdRuleSet doesn't work for http urls

### ISSUE THREAD

**Issue by count-negative** [m2e-code-quality/m2e-code-quality#6]
the  URL resolvedLocation = resourceResolver.resolveLocation(loc); throws a NPE if there is a ruleset configured like
<ruleset>http://localhost/design.xml</ruleset> or on a local disk <ruleset>pmd.xml</ruleset>

**Comment by ArloL** [comment]
Hi @count-negative, I am trying to cleanup the issues. Is this still a problem? Please let me know and I will look into it.

**Comment by count-negative** [comment]
Bwa dont't know. It's been too long so please close.
