### ISSUE TITLE
Can not install m2e code quality to STS

### ISSUE THREAD

**Issue by selmantayyar** [m2e-code-quality/m2e-code-quality#62]
I can not install the plugin into STS.Information and eror message below:
Spring Tool Suite 
Version: 3.6.3.RELEASE
Build Id: 201411281415
Platform: Eclipse Luna SR1 (4.4.1)

![m2e](https://cloud.githubusercontent.com/assets/1129967/5631968/2598c86e-95cb-11e4-8f1b-fe7f97c51878.png)

Hope information is enough.
Please let me know.

**Comment by ArloL** [comment]
Please try this site http://m2e-code-quality.github.io/m2e-code-quality/site/develop/

**Comment by ArloL** [comment]
I have released a new version since everything works for me: http://m2e-code-quality.github.io/m2e-code-quality/site/latest

Please re-open the issue if it still doesnt work.

**Comment by selmantayyar** [comment]
It is working now.
Thanks for prompt action.
Cheers
