### ISSUE TITLE
Regression: Checkstyle configuration is not loaded with recent plugin version

### ISSUE THREAD

**Issue by antonsmyk** [m2e-code-quality/m2e-code-quality#68]
Have fresh install Eclipse Luna SR1 with last updates. Installed the m2-code-quality plugin from http://m2e-code-quality.github.io/m2e-code-quality/site/latest. Imported Maven project which uses custom checkstyle configuration resolved from classpath as below:
```
    <properties>
        <maven-checkstyle-plugin.version>2.12.1</maven-checkstyle-plugin.version>
        <checkstyle.config.location>checkstyle.xml</checkstyle.config.location>
        <checkstyle.suppressions.location>checkstyle-suppress.xml</checkstyle.suppressions.location>
    </properties>
...
    <build>
        <pluginManagement>
            <plugins>
...
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-checkstyle-plugin</artifactId>
                    <version>${maven-checkstyle-plugin.version}</version>
                    <dependencies>
                        <dependency>
                            <groupId>com.orcsoftware.maven.plugins</groupId>
                            <artifactId>checkstyle-config</artifactId>
                            <version>${orcsoftware.checkstyle-config.version}</version>
                        </dependency>
                    </dependencies>
                    <configuration>
                        <includeTestSourceDirectory>true</includeTestSourceDirectory>
                        <failOnViolation>true</failOnViolation>
                        <logViolationsToConsole>true</logViolationsToConsole>
                    </configuration>
                </plugin>
...
            </plugins>
        </pluginManagement>
    </build>
```

Problem is that custom checkstyle configuration is not picked by the plugin. Refer to the screenshot. No difference with versions 2.9.1 or latest 2.13 of maven-checkstyle-plugin.

![checkstyle-bad](https://cloud.githubusercontent.com/assets/10366539/5708159/0d663e02-9a8f-11e4-8662-014fb30c89af.png)

When, instead, I add software site http://sourceforge.net/projects/eclipse-cs/files/updatesite/5.7.0/ and install from http://m2e-code-quality.github.io/m2e-code-quality/site/1.0.0, then checkstyle configuration is picked up properly (see another screenshot.)

![checkstyle-good](https://cloud.githubusercontent.com/assets/10366539/5708162/1a7cea50-9a8f-11e4-820f-7b16f761d9f2.png)

However there is problem with this workaround so that Eclipse updates can not be installed anymore.

**Comment by ArloL** [comment]
Please try with the latest develop build:

http://m2e-code-quality.github.io/m2e-code-quality/site/develop/

**Comment by antonsmyk** [comment]
Thanks, it now works!

Would you please release a stable version then?

**Comment by ArloL** [comment]
I will release Friday in a week since I won't have the chance to react to bugs until then.

**Comment by balazs-zsoldos** [comment]
Same issue with newest version of Eclise (4.2.2), m2e-checkstyle (1.0.0.201503101518) and Eclise Checkstyle plugin (6.5.0.201504121610).

**Comment by balazs-zsoldos** [comment]
Found the issue. It was because exlude directory pattern from maven config could not be handled. It was really hard to find it (only via debugging) as CheckstylePluginException is swallowed in EclipseCheckstyleProjectConfigurator

**Comment by c4n70r** [comment]
Hi there, 
I'm facing the same problem with 

Eclipse Checkstyle Plug-in, 6.11.1.201510102004	
Checkstyle configuration plugin for M2Eclipse	, 1.0.0.201503101518
m2e 1.6.2
Eclipse  Mars 4.5.1

is there already a workaround or a fix available?

**Comment by ArloL** [comment]
Sorry about the delay. I've just pushed a new release. Please let me know if it was fixed or whether the issue still exists!

**Comment by balazs-zsoldos** [comment]
Everything works well for me. Thanks!

**Comment by c4n70r** [comment]
hm, makes no difference on my projects.
I have a multi module project which is using a build-tools artifact (see https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/multi-module-config.html)

After deleting all eclipse configuration files from the tree (.project, .classpath, .settings/ , .pmdruleset.xml) and deleting the projects from eclipse, I've imported them via m2e.
PMD is configured and a builder is added - but for checkstyle nothing happened.

**Comment by ArloL** [comment]
@balazs-zsoldos Thanks for the feedback. Glad it's working for you!

@c4n70r Could you maybe create a PR with a project in the test-projects directory that demonstrates your problem?

**Comment by c4n70r** [comment]
@ArloL done

**Comment by ArloL** [comment]
Thanks, @c4n70r. I will look into it.

**Comment by ArloL** [comment]
Here's what I did:

1. New Mars with Eclipse Installer
2. Import all maven projects
3. Install m2e connectors, checkstyle and pmd after Eclipse recommends it
4. Restart Eclipse. I then get an error message that some stuff can't be found.
4. `mvn install` on build-tools
5. Maven -> Update Project
6. Properties of example-persistence -> Checkstyle. See that it has the right file from my m2 repository.

Does that not work for you or don't you want to `mvn install` on build-tools?

**Comment by c4n70r** [comment]
I did the nearly same, but used the eclipse Mars.1 zip package and had the PMD and Checkstyle Plugins allready installed before importing the project.
I also did a mvn  clean install in the console before importing.
PMD is active, checkstyle is not configured.
maybe ist one of the other plugins?
- moreunit
- infiniitest
- mousefeed

**Comment by ArloL** [comment]
Could be. Please try if you can follow my steps above and send me a screenshot of the checkstyle config and Eclipse Error Log.

**Comment by c4n70r** [comment]
1.) unpacked eclipse-jee-mars-1-win32-x86_64.zip
2.) git clone https://github.com/c4n70r/m2e-code-quality.git
3.) started eclipse with new workspace
4.) import existing maven projects from
 %projectspath%\m2e-code-quality-new\m2e-code-quality\test-projects\failing-checkstyle-example
5.) eclipse installs pmd and checkstyle m2e configurators and eclipse
pmd and eclipse-cs plugins
6.) restart eclipse
7.) pmd is configured (with ecipse builderand  .pmd and .pmdruleset.xml
config files) eclipse-cs not.
8.) Maven -> Update Project
9.) goto 7.)

:-/

screenshots are attached

**Comment by ArloL** [comment]
Sadly I can't see any screenshots.

**Comment by c4n70r** [comment]
doesnt work, please check your gmail account.

**Comment by ArloL** [comment]
It seems to be a problem with the SuppressionFilter. I have no time anymore so if you want to look into this and maybe come up with a fix I'll gladly release it.

I've got as far as setting the SuppressionFilter to ${checkstyle.suppressions.file} that way I can import the projects. I've boiled my progress down in checkstyle-5. Please check it out and see that the suppressionsFilter is setup with the property. Now we only have to fix that the m2e-connector code resolves that property properly.

**Comment by c4n70r** [comment]
So, no soulution on a silver tray ;-) 
This week is pretty full. But I'll see if I can help, I need that plugin anyway.
Unfortunately the only thing I know about OSGI (and Tycho) is, that it supposedly exists .

**Comment by ArloL** [comment]
I just tried checkstyle-5 again with a clean checkout and a clean eclipse. It seems that `${checkstyle.suppressions.file}` does the trick. It loads the correct suppressions file from both the command line and in Eclipse. Could you try that? I updated checkstyle-5 accordingly.

**Comment by antonsmyk** [comment]
I confirm both that checkstyle configuration is loaded now (thanks ArloL!) and that suppressions don't. 

We use `checkstyle.suppressions.location` property, not `checkstyle.suppressions.file` since latter is deprecated and doesn't support loading from classpath (indeed, in Maven build we do load both checkstyle config and suppressions from classpath).

I am not sure if loading suppressions into Eclipse ever worked before. I tried to check with older version, but installing 1.0.0 release fails in Eclipse, and Maven build for tag 1.0.0.201408150901 also fails due to inaccessible repos.

**Comment by ArloL** [comment]
@antonsmyk Thanks for your confirmation. Where are you using the `checkstyle.suppressions.location` property? In checkstyle-5 these are the two critical lines that make suppressions work both in maven and in m2e: https://github.com/m2e-code-quality/m2e-code-quality/blob/66b73db40d7810b2adb984767f314ac3558c58d6/test-projects/checkstyle-5/project-using-checkstyle-config/pom.xml#L34 and https://github.com/m2e-code-quality/m2e-code-quality/blob/66b73db40d7810b2adb984767f314ac3558c58d6/test-projects/checkstyle-5/checkstyle-config/src/main/resources/checkstyle.xml#L32.

With that configuration this is what my eclipse looks like

![screen shot 2016-02-10 at 21 56 43](https://cloud.githubusercontent.com/assets/195367/12961526/393d1e54-d041-11e5-9dd7-ba94926f10a8.png)

Therefore I assume that everything is working correctly here. Or is there something that I missed?

**Comment by c4n70r** [comment]
Thats it! 
Just tried the checkstyle-5 project and then adapted the ${checkstyle.suppressions.file} setting to my current work project with 30+ modules with subsubmodules. 
It worked on my actual eclipse configuration with an already configured workspace and lots of plugins, so this was no lab test ;-)
@ArloL Thank you so much!
Have a nice day.

**Comment by antonsmyk** [comment]
@ArloL, I've raised separate issue #80 about suppressions from classpath problem.

**Comment by ArloL** [comment]
@c4n70r Glad it's working for you.

@antonsmyk Since you've opened the other issue I will close this one.
