### ISSUE TITLE
Plugin cannot add suppression file properly

### ISSUE THREAD

**Issue by WonderCsabo** [m2e-code-quality/m2e-code-quality#69]
I have this config in my POM:
```xml
<suppressionsLocation>checkstyle-suppressions.xml</suppressionsLocation>
```

This results in an additional property added to the local check configuration:
```
checkstyle.suppressions.file=<a_correct_path>
```

However, this does not make a difference, and `eclipse-cs` still checks all my classes. Actually i searched for this property, and i did not found anything about it. How this should make cs recognize the suppression file?

If i add the suppression filter manually, it does work. It also works from command line.

**Comment by WonderCsabo** [comment]
I managed to solve the problem. I have to add the following module to the Checkstyle ruleset:
```xml
<module name="SuppressionFilter">
    <property name="file" value="${checkstyle.suppressions.file}"/>
</module>
```
Thanks to @lkoe for the [suggestion](https://sourceforge.net/p/eclipse-cs/discussion/274377/thread/218b9c12/)

BTW, [`checkstyle.suppressions.file`](https://maven.apache.org/plugins/maven-checkstyle-plugin/checkstyle-mojo.html#suppressionsFile) property is deprecated, the plugin should use [`checkstyle.suppressions.location`](https://maven.apache.org/plugins/maven-checkstyle-plugin/checkstyle-mojo.html#suppressionsLocation) instead!

**Comment by ArloL** [comment]
Hi @WonderCsabo, I was wondering whether this issue can be closed?

The maven properties `checkstyle.suppressions.file` and `checkstyle.suppressions.location` both work. `${checkstyle.suppressions.file}` in `checkstyle.xml` has nothing to do with the maven property. It's checkstyle-specific. See the official [checkstyle.xml](https://github.com/checkstyle/checkstyle/blob/9d90fa25e0087282d2fe3d4f09835a36c70d8f8b/config/checkstyle_checks.xml#L37) for reference.

BTW Great work with androidannotations and @dodgex is one of my colleagues :)

**Comment by WonderCsabo** [comment]
In the `maven-checkstyle-plugin` configuration, you can [define](https://maven.apache.org/plugins/maven-checkstyle-plugin/check-mojo.html#suppressionsLocation) the suppressions file in the POM directly:
```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-checkstyle-plugin</artifactId>
	<configuration>
		<configLocation>${main.basedir}/checkstyle-checks.xml</configLocation>
		<suppressionsLocation>${main.basedir}/checkstyle-suppressions.xml</suppressionsLocation>
		<consoleOutput>true</consoleOutput>
		<linkXRef>false</linkXRef>
		<includeTestSourceDirectory>true</includeTestSourceDirectory>
	</configuration>
</plugin>
```

This is working even if you do not add a `SuppressionFilter` in the Checkstyle configuration file.

**Comment by ArloL** [comment]
Thanks for clarifying. It doesn't seem like there is a way to do this in eclipse-cs. I don't believe that the connector should work around that fact. Would you create an issue at the eclipse-cs project? Or is it not that important for you? I personally don't think it's that important but I will try implementing it if eclipse-cs adds the feature.

**Comment by WonderCsabo** [comment]
I think the workaround i wrote in https://github.com/m2e-code-quality/m2e-code-quality/issues/69#issuecomment-100625141 is acceptable, so i do not think anything should be implemented. That is the plain Checkstyle solution anyway.

**Comment by ArloL** [comment]
Sounds good to me. I'll close this issue then.
