### ISSUE TITLE
Disable adding FindBugs nature when the project type is EAR

### ISSUE THREAD

**Issue by trajano** [m2e-code-quality/m2e-code-quality#70]
Seems that the FindBugs configurator tries to add the nature and is giving the following error in the logs
<pre>
Java project is not open or does not exist: P/[project name]
</pre>

**Comment by donsenior** [comment]
This bug is pretty annoying when having an ear module, because on every build, it pops up a **"Problem Ocurred"** dialog, with message **"Finding bugs in [project name]"** and the detail message that @trajano has already mentioned.

**Comment by dojcsak** [comment]
I think PR #73 may solve the problem!

**Comment by ArloL** [comment]
Sorry about the delay. I've just pushed a new release. Please let me know if it was fixed or whether the issue still exists!

**Comment by ArloL** [comment]
Since I haven't heard anything back for three months I'll go ahead and assume it works now. Otherwise simply open a new issue or reopen this one.
