### ISSUE TITLE
Failed to resolve target definition m2e-code-quality/mars/mars.target: Could not find "net.sf.eclipsecs.feature.group/6.14.0.201602102232" in the repositories of the current location

### ISSUE THREAD

**Issue by vorburger** [m2e-code-quality/m2e-code-quality#84]
m2e-code-quality currently (as of today f8e36f0f6fa5fa618624ac674279a181d87834cd) fails to build:

    git clone https://github.com/m2e-code-quality/m2e-code-quality
    cd m2e-code-quality
    mvn clean install
    (...)
    [ERROR] Failed to resolve target definition /home/vorburger/dev/github/m2e-code-quality/m2e-code-quality/mars/mars.target: Could not find "net.sf.eclipsecs.feature.group/6.14.0.201602102232" in the repositories of the current location -> [Help 1]

Is someone actively maintaining m2e-code-quality and would like to address this?

**Comment by vorburger** [comment]
This gets fixed by https://github.com/m2e-code-quality/m2e-code-quality/pull/86

PS: Do you know about https://wiki.eclipse.org/Eclipse_Oomph_Authoring#Generating_PDE_Target_Definition_files_.28.2A.target.29_and_their_use_by_Tycho ? That allows you to auto generate those pesky *.target files from the Oomph *.setup model, and avoids the issue with the hard-coded version numbers required in the *.target files ...

**Comment by ArloL** [comment]
I can't find information on whether the oomph generation works with the command line build in travis-ci. Could you find anything?

AFAIR there already is a target in the oomph setup model that does not use version numbers, no?

**Comment by ArloL** [comment]
Since I couldn't find any information on generating the target platform for the maven builds I will close this issue. If you find anything new @vorburger please re-open. Thanks!
