### ISSUE TITLE
nullpointerexception on projects without local ressources

### ISSUE THREAD

**Issue by afischer211** [m2e-code-quality/m2e-code-quality#89]
If you have a project only with remote checkstyle-ressources (or ressources like checkstyle-rules downloaded from http-server during maven-build), the m2e-connector for checkstyle crashes with a NullPointerException.
I have patched the class com.basistech.m2e.code.quality.shared.ResourceResolver in method public URL getResourceFromPluginRealm(final String resource);

How can I distribute the patched code? I made some mistakes on creating my first pull-request...

**Comment by afischer211** [comment]
I have patched the code in my own fork of this repository. The code is compileable and works for me.

**Comment by ArloL** [comment]
Thanks for reporting and taking the time to fix the issue!

I've fixed the problem with https://github.com/m2e-code-quality/m2e-code-quality/commit/a093d82da0ea9376128833136a90d6ec7fb74410.

https://help.github.com/articles/using-pull-requests/ might help you in future!

**Comment by ArloL** [comment]
This is now available in the snapshot update site: https://m2e-code-quality.github.io/m2e-code-quality/site/develop/

If you could test it and report back that everything works, that would be great. Thanks in advance.

**Comment by ArloL** [comment]
Hi, @afischer211. Did you get a chance to test this?

**Comment by ArloL** [comment]
The snapshot has been released now. Please let me know if there are any issues.
