### ISSUE TITLE
EclipsePmdProjectConfigurator.createPmdRuleSet dereferences a null pointer if the ruleset path is not found

### ISSUE THREAD

**Issue by ianbollinger** [m2e-code-quality/m2e-code-quality#9]
Namely, on line #223, the local `resolvedLocation` can be `null`. Also, project-relative paths didn't seem to work for me; qualifying it with `${basedir}` fixed the issue.

**Comment by ArloL** [comment]
Hi @ianbollinger, I want to cleanup the issues. Has this been fixed by #19? Please let me know if not and I will look into it.

**Comment by ArloL** [comment]
Since I haven't heard anything back for three months I'll go ahead and assume it works now. Otherwise simply open a new issue or reopen this one.
