### ISSUE TITLE
problems under Windows with m2e-connector for checkstyle

### ISSUE THREAD

**Issue by afischer211** [m2e-code-quality/m2e-code-quality#90]
The resolving of relative paths from absolute paths don't work correctly under Windows (here you have drive letters and other path-separators).
I have a first solution based on nio.Path and nio.Paths, but there are more problems with the patterns itself (e.g. the methods convertToEclipseCheckstyleRegExpPath() and normalizePatternsToCheckstyleFileMatchPattern() in class com.basistech.m2e.code.quality.checkstyle.MavenPluginConfigurationTranslator).
How can I distribute my code-suggestions?

**Comment by afischer211** [comment]
You can take a look at my modifications in my own fork of this repository.

**Comment by ArloL** [comment]
Thanks for reporting the issue!

I would like to reproduce this problem myself first. Could you create an example project that demonstrates the problems you're seeing on Windows?

**Comment by ArloL** [comment]
Hey, @afischer211. Did you get a chance to look into this yet?

**Comment by afischer211** [comment]
Hello, at the moment I have not so much time for this.
I try to create a small demo-project and add this as an attachment.
But my first idea is a problem with defined excludes in the pom for folders under the target-folder (e.g. created sources) and the resolving of this excludes as full path-values.

**Comment by ArloL** [comment]
That's fine. I will keep the issue open for another month. If you don't find the time until then you can just re-open it after that.

**Comment by ArloL** [comment]
I will close the issue now. Please just re-open if you find the time to create a demonstration project.
