### ISSUE TITLE
One config for src/main/ and one for src/test/

### ISSUE THREAD

**Issue by anton-johansson** [m2e-code-quality/m2e-code-quality#92]
I have a checkstyle configuration that looks something like this:
```xml
                <executions>
                    <execution>
                        <id>checkstyle-main</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <includeTestSourceDirectory>false</includeTestSourceDirectory>
                            <includeResources>true</includeResources>
                            <includeTestResources>false</includeTestResources>
                            <configLocation>checkstyle-main.xml</configLocation>
                            <violationSeverity>warning</violationSeverity>
                        </configuration>
                    </execution>
                    <execution>
                        <id>checkstyle-test</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <includeTestSourceDirectory>true</includeTestSourceDirectory>
                            <includeResources>false</includeResources>
                            <includeTestResources>true</includeTestResources>
                            <configLocation>checkstyle-test.xml</configLocation>
                            <violationSeverity>warning</violationSeverity>
                        </configuration>
                    </execution>
                </executions>
```

This generates awesome configuration inside Eclipse. However, I have one small issue. The ```checkstyle-test``` execution adds the following ```File Matching Regular Expression``` in Eclipse:

- src/main/java/.*\.java
- src/test/java/.*\.java
- src/test/resources/.*\.properties

I want the first one to go away, but I've found no solution that works well. Is there a solution?

This is perhaps not the correct place to ask this question, I'm not sure this is possible in ```maven-checkstyle-plugin``` at all.

**Comment by ArloL** [comment]
Hi @anton-johansson,

thanks for reporting your issue. I was wondering whether your configuration works on the command line? That would be interesting for me to know since the connector and the command line should produce the same results.

Have you tried setting `https://maven.apache.org/plugins/maven-checkstyle-plugin/checkstyle-mojo.html#sourceDirectories` to not include /src/main/java in your test configuration?

**Comment by anton-johansson** [comment]
Well, my current solution sort of works in command line, in the sense that it will only execute the first execution if it fails. So it won't show double warnings. But that is obviously not possible in the Eclipse Plugin, and since I am not saying my execution NOT to execute test-checks in the main-folder, it will show me double warnings.

Okay, so I tried using ```sourceDirectories``` and came up with this configuration:
```xml
                    <execution>
                        <id>checkstyle-main</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <sourceDirectories>
                                <sourceDirectory>src/main/</sourceDirectory>
                            </sourceDirectories>
                            <configLocation>viskan-checkstyle-main.xml</configLocation>
                            <violationSeverity>warning</violationSeverity>
                        </configuration>
                    </execution>
                    <execution>
                        <id>checkstyle-test</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <sourceDirectories>
                                <sourceDirectory>src/test/</sourceDirectory>
                            </sourceDirectories>
                            <configLocation>viskan-checkstyle-test.xml</configLocation>
                            <violationSeverity>warning</violationSeverity>
                        </configuration>
                    </execution>
```

This seems to work perfectly in Command Line. I can guarantee that the test-execution does NOT look inside the main folder. But the Eclipse plugin gives me these ```File matching Regular Expression```s for both executions:
 * src/main/java/.*.java
 * src/main/resources/.*.properties
 * src/test/resources/.*.properties

So I guess there's a small issue there?

**Comment by anton-johansson** [comment]
Anyone have any ideas or suggestions?

**Comment by ArloL** [comment]
Which version of the connector are you using? The latest or the develop? There is a fix in the develop that works around a problem with the default value of sourceDirectories: https://github.com/m2e-code-quality/m2e-code-quality/commit/3a87bd9a939c35a5d4408342d0491906769da648

You can install the snapshot from https://m2e-code-quality.github.io/m2e-code-quality/site/develop/

**Comment by anton-johansson** [comment]
I'm using ```6.16.0.201603042321``` in my Eclipse. Cool, I will try it and let you know!

**Comment by ArloL** [comment]
That seems to be the version of the checkstyle plugin. You want the version of the m2e connector which would be something like 1.0.0.2016XXX

**Comment by anton-johansson** [comment]
Oh, of course. Looking at my ```Eclipse Installation Details``` and then ```Plug-Ins```, I can find this one:

| Plug-in Name  | Version | Plug-in Id |
| ------------- | ------------- | ------------- |
| M2Eclipse Project Configuration for Eclipse Checkstyle  | 1.0.0.201602071612  | com.basistech.m2e.code.quality.checkstyle |

Is this the one you're looking for?

**Comment by ArloL** [comment]
Yes, that's the one. You want to install the snapshot so that the version is 1.0.0.201605301854

Just add the update site https://m2e-code-quality.github.io/m2e-code-quality/site/develop/ and install the update.

**Comment by ArloL** [comment]
Did it work, @anton-johansson?

**Comment by anton-johansson** [comment]
Sorry for the delay, @ArloL. I just tested the snapshot version and it works much better! However, I still got resources from both test and main. But that was easily solved with these two:
```xml
<includeResources>false</includeResources>
<includeTestResources>false</includeTestResources>
```

Final XML:
```xml
<executions>
    <execution>
        <id>checkstyle-main</id>
        <goals>
            <goal>check</goal>
        </goals>
        <configuration>
            <sourceDirectories>
                <sourceDirectory>src/main/java/</sourceDirectory>
            </sourceDirectories>
            <includeResources>true</includeResources>
            <includeTestResources>false</includeTestResources>
            <configLocation>checkstyle-main.xml</configLocation>
            <violationSeverity>warning</violationSeverity>
        </configuration>
    </execution>
    <execution>
        <id>checkstyle-test</id>
        <goals>
            <goal>check</goal>
        </goals>
        <configuration>
            <sourceDirectories>
                <sourceDirectory>src/test/java/</sourceDirectory>
            </sourceDirectories>
            <includeResources>false</includeResources>
            <includeTestResources>true</includeTestResources>
            <configLocation>checkstyle-test.xml</configLocation>
            <violationSeverity>warning</violationSeverity>
        </configuration>
    </execution>
</executions>
```

Thanks for the help!

Will you release a new version anytime soon? No biggie though, I can go on using the snapshot, just curious.

**Comment by ArloL** [comment]
I would love to release but I am still waiting for feedback on some big changes I made (#39 and #40). If I don't get any feedback in the next two weeks I will just release and hope for the best.

**Comment by anton-johansson** [comment]
Allright, sounds good!

**Comment by ArloL** [comment]
@anton-johansson I just released the change. Please let me know if there are any issues.
